package Vista;

import Controlador.Gestion;
import Modelo.MiTablaEscaneados;
import javax.swing.JOptionPane;

/**
 *
 * @author Ainhoa
 */
public class PantallaAplicacion extends javax.swing.JDialog {

    /**
     * Creates new form PantallaAplicacion
     */
    Gestion gestion = new Gestion();

    public PantallaAplicacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSelectUnity = new javax.swing.JButton();
        jButtonDeleteEmplyDirectory = new javax.swing.JButton();
        jButtonShowFreeSpace = new javax.swing.JButton();
        jButtonDeleteRecycle = new javax.swing.JButton();
        jButtonDeleteBrowsingHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArchivosRecursivos = new javax.swing.JTable();
        jButtonDeleteImages = new javax.swing.JButton();
        jButtonDeleteVideo = new javax.swing.JButton();
        jButtonBorrarPorTamanio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonSelectUnity.setText("<html><center>Seleccionar Unidad<br> y mostrar contenido </br></center></html>");
        jButtonSelectUnity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectUnityActionPerformed(evt);
            }
        });

        jButtonDeleteEmplyDirectory.setText("Eliminar directorios vacíos");
        jButtonDeleteEmplyDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteEmplyDirectoryActionPerformed(evt);
            }
        });

        jButtonShowFreeSpace.setText("<html><center>Mostrar espacio libre <br> en disco</center</html>");
        jButtonShowFreeSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowFreeSpaceActionPerformed(evt);
            }
        });

        jButtonDeleteRecycle.setText("Vaciar la papelera");
        jButtonDeleteRecycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRecycleActionPerformed(evt);
            }
        });

        jButtonDeleteBrowsingHistory.setText("Eliminar historial de navegación");
        jButtonDeleteBrowsingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBrowsingHistoryActionPerformed(evt);
            }
        });

        jTableArchivosRecursivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableArchivosRecursivos);

        jButtonDeleteImages.setText("Borrar Imagenes");
        jButtonDeleteImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteImagesActionPerformed(evt);
            }
        });

        jButtonDeleteVideo.setText("Borrar videos");
        jButtonDeleteVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteVideoActionPerformed(evt);
            }
        });

        jButtonBorrarPorTamanio.setText("Borrar por tamaño");
        jButtonBorrarPorTamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarPorTamanioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonSelectUnity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonShowFreeSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDeleteBrowsingHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteRecycle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteEmplyDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBorrarPorTamanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteImages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDeleteEmplyDirectory)
                            .addComponent(jButtonDeleteImages))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDeleteRecycle)
                            .addComponent(jButtonDeleteVideo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDeleteBrowsingHistory)
                            .addComponent(jButtonBorrarPorTamanio))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSelectUnity, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonShowFreeSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void rellenarTabla() {
        jTableArchivosRecursivos.setModel(new MiTablaEscaneados(gestion.getListaParaMetodoRecursivo()));
    }
    private void jButtonSelectUnityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectUnityActionPerformed
        gestion.getListaParaMetodoRecursivo().clear();
        rellenarTabla();
        gestion.selectUnity(this);
        JOptionPane.showMessageDialog(this, "Estas en la ruta " + gestion.getFile().getAbsolutePath());
        gestion.listarRecursivo(gestion.getFile().getAbsolutePath());
        gestion.getListaParaMetodoRecursivo();
        rellenarTabla();
    }//GEN-LAST:event_jButtonSelectUnityActionPerformed

    private void jButtonDeleteEmplyDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteEmplyDirectoryActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "¿Desea borrar los directorios vacíos de esta ruta?", "Borrar directorios", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            gestion.deleteEmptyDirectoriesR(gestion.getFile().getAbsolutePath());
            JOptionPane.showMessageDialog(this, "Se han borrado " + gestion.getContadorDirectoriosVaciosBorrados() + " directorios vacíos.");
        } else {
            JOptionPane.showMessageDialog(this, "No se han borrado los directorios.");
        }

    }//GEN-LAST:event_jButtonDeleteEmplyDirectoryActionPerformed

    private void jButtonShowFreeSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowFreeSpaceActionPerformed
        gestion.checkDiskSpace();
        JOptionPane.showMessageDialog(this, "Espacio total del disco: " + gestion.getTotal() / 1024 / 1024 / 1024 + "GB" + "\n" + "Espacio libre en disco: " + gestion.getLibre() / 1024 / 1024 / 1024 + "GB");
    }//GEN-LAST:event_jButtonShowFreeSpaceActionPerformed

    private void jButtonDeleteRecycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRecycleActionPerformed
        int borrados = gestion.emptyTrash();
        JOptionPane.showMessageDialog(this, "Se han borrado " + borrados + " archivos de la papelera.");

    }//GEN-LAST:event_jButtonDeleteRecycleActionPerformed

    private void jButtonDeleteBrowsingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBrowsingHistoryActionPerformed
        SeleccionarNavegador sn = new SeleccionarNavegador(this, true, gestion);
        sn.setVisible(true);
    }//GEN-LAST:event_jButtonDeleteBrowsingHistoryActionPerformed

    private void jButtonDeleteImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteImagesActionPerformed
        int imagenesBorradas = gestion.deleteImages();
        JOptionPane.showMessageDialog(this, "Se han borrado " + imagenesBorradas + " imágenes.");
        rellenarTabla();
    }//GEN-LAST:event_jButtonDeleteImagesActionPerformed

    private void jButtonDeleteVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteVideoActionPerformed
      int videosBorrados = gestion.deleteVideos();
      JOptionPane.showMessageDialog(this, "Se han borrado " + videosBorrados + " videos.");
      rellenarTabla();
      
    }//GEN-LAST:event_jButtonDeleteVideoActionPerformed

    private void jButtonBorrarPorTamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarPorTamanioActionPerformed
       BorrarPorTamanio bt = new BorrarPorTamanio(this, true, gestion);
       bt.setVisible(true);
    }//GEN-LAST:event_jButtonBorrarPorTamanioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarPorTamanio;
    private javax.swing.JButton jButtonDeleteBrowsingHistory;
    private javax.swing.JButton jButtonDeleteEmplyDirectory;
    private javax.swing.JButton jButtonDeleteImages;
    private javax.swing.JButton jButtonDeleteRecycle;
    private javax.swing.JButton jButtonDeleteVideo;
    private javax.swing.JButton jButtonSelectUnity;
    private javax.swing.JButton jButtonShowFreeSpace;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArchivosRecursivos;
    // End of variables declaration//GEN-END:variables
}
