/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GestionCarrera;
import Modelo.Carrera;
import java.io.Serializable;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ainhoa
 */
public class CuestionarioAltaCarreras extends javax.swing.JDialog implements Serializable {

    /**
     * Creates new form CuestionarioAltaCarreras
     */
    private GestionCarrera gc;
    private Carrera carreraNueva;
    private Carrera carreraModificar;

    public CuestionarioAltaCarreras(java.awt.Dialog parent, boolean modal, GestionCarrera gc) {
        super(parent, modal);
        this.gc = gc;
        initComponents();
        setLocationRelativeTo(this);
        //falta validarFormulario();
    }

    public CuestionarioAltaCarreras(java.awt.Dialog parent, boolean modal, Carrera carreraModificar) {
        super(parent, modal);
        this.carreraModificar = carreraModificar;
        initComponents();
        jTextFieldNombreCarrera.setText(this.carreraModificar.getNombreCarrera());
        jTextFieldLugar.setText(this.carreraModificar.getLugarCarrera());
        jTextFieldNumeroParticipantes.setText(Integer.toString(this.carreraModificar.getNumeroParticipantes()));
        jTextFieldPrecio.setText(Double.toString(this.carreraModificar.getPrecio()));
        jDateChooserFecha.setDate(this.carreraModificar.getFechaCarrera());
        //falta validarFormulario();
    }

    private void limpiarPantalla() {
        jTextFieldNombreCarrera.setText("");
        jTextFieldLugar.setText("");
        jTextFieldNumeroParticipantes.setText("");
        jTextFieldPrecio.setText("");
        jDateChooserFecha.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloCuestionarioCarreras = new javax.swing.JLabel();
        jLabelNombreCarrera = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelLugar = new javax.swing.JLabel();
        jLabelNumeroParticipantes = new javax.swing.JLabel();
        jTextFieldNombreCarrera = new javax.swing.JTextField();
        jTextFieldLugar = new javax.swing.JTextField();
        jTextFieldNumeroParticipantes = new javax.swing.JTextField();
        validationPanelAltaCarrrera = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jButtonEnviarCarreras = new javax.swing.JButton();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jTextFieldPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTituloCuestionarioCarreras.setFont(new java.awt.Font("Calibri Light", 3, 36)); // NOI18N
        jLabelTituloCuestionarioCarreras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloCuestionarioCarreras.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jLabelTituloCuestionarioCarreras.text")); // NOI18N

        jLabelNombreCarrera.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jLabelNombreCarrera.text")); // NOI18N

        jLabelFecha.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jLabelFecha.text")); // NOI18N

        jLabelLugar.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jLabelLugar.text")); // NOI18N

        jLabelNumeroParticipantes.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jLabelNumeroParticipantes.text")); // NOI18N

        jTextFieldNombreCarrera.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jTextFieldNombreCarrera.text")); // NOI18N

        jTextFieldLugar.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jTextFieldLugar.text")); // NOI18N

        jTextFieldNumeroParticipantes.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jTextFieldNumeroParticipantes.text")); // NOI18N
        jTextFieldNumeroParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroParticipantesActionPerformed(evt);
            }
        });

        jButtonEnviarCarreras.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jButtonEnviarCarreras.text")); // NOI18N
        jButtonEnviarCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarCarrerasActionPerformed(evt);
            }
        });

        jTextFieldPrecio.setText(org.openide.util.NbBundle.getMessage(CuestionarioAltaCarreras.class, "CuestionarioAltaCarreras.jTextFieldPrecio.text")); // NOI18N
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTituloCuestionarioCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFecha)
                                            .addComponent(jLabelLugar))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelNombreCarrera)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooserFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNumeroParticipantes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumeroParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(validationPanelAltaCarrrera, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEnviarCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelTituloCuestionarioCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validationPanelAltaCarrrera, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreCarrera))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFecha)
                            .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLugar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroParticipantes)
                            .addComponent(jTextFieldNumeroParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(jButtonEnviarCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarCarrerasActionPerformed

        String nombreCarrera = jTextFieldNombreCarrera.getText();
        Date fechaCarrera = jDateChooserFecha.getDate();
        String lugarCarrera = jTextFieldLugar.getText();
        double precioCarrera = Double.valueOf(jTextFieldPrecio.getText());
        int numeroParticipantes = Integer.parseInt(jTextFieldNumeroParticipantes.getText());

        carreraNueva = new Carrera(nombreCarrera, fechaCarrera, lugarCarrera, numeroParticipantes, precioCarrera);

        if (carreraModificar == null) {
            gc.anadirCarrera(nombreCarrera, fechaCarrera, lugarCarrera, numeroParticipantes, precioCarrera);
            JOptionPane.showMessageDialog(this, "Carrera dada de alta", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            carreraModificar.setNombreCarrera(nombreCarrera);
            carreraModificar.setLugarCarrera(lugarCarrera);
            carreraModificar.setNumeroParticipantes(numeroParticipantes);
            carreraModificar.setPrecio(precioCarrera);
            carreraModificar.setFechaCarrera(fechaCarrera);
        }

        limpiarPantalla();
        dispose();
    }//GEN-LAST:event_jButtonEnviarCarrerasActionPerformed

    private void jTextFieldNumeroParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroParticipantesActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarCarreras;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelLugar;
    private javax.swing.JLabel jLabelNombreCarrera;
    private javax.swing.JLabel jLabelNumeroParticipantes;
    private javax.swing.JLabel jLabelTituloCuestionarioCarreras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldNombreCarrera;
    private javax.swing.JTextField jTextFieldNumeroParticipantes;
    private javax.swing.JTextField jTextFieldPrecio;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanelAltaCarrrera;
    // End of variables declaration//GEN-END:variables
}
