package Vista;

import Controlador.Gestion;
import java.io.File;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Ainhoa
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    Gestion gestion = new Gestion();

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSelectU = new javax.swing.JButton();
        jButtonDeleteEmplyDirectory = new javax.swing.JButton();
        jButtonShowFreeSpace = new javax.swing.JButton();
        jLabelSelect = new javax.swing.JLabel();
        jButtonDeleteRecycle = new javax.swing.JButton();
        jButtonDeleteBrowsingHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSelectU.setText("<html><center>Seleccionar Unidad<br> y mostrar contenido </br></center></html>");
        jButtonSelectU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectUActionPerformed(evt);
            }
        });

        jButtonDeleteEmplyDirectory.setText("Eliminar directorios vacíos");
        jButtonDeleteEmplyDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteEmplyDirectoryActionPerformed(evt);
            }
        });

        jButtonShowFreeSpace.setText("<html><center>Mostrar espacio libre <br> en disco</center</html>");
        jButtonShowFreeSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowFreeSpaceActionPerformed(evt);
            }
        });

        jButtonDeleteRecycle.setText("Vaciar la papelera");
        jButtonDeleteRecycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRecycleActionPerformed(evt);
            }
        });

        jButtonDeleteBrowsingHistory.setText("Eliminar historial de navegación");
        jButtonDeleteBrowsingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBrowsingHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButtonSelectU, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonShowFreeSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDeleteEmplyDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteRecycle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteBrowsingHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSelectU, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDeleteEmplyDirectory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteRecycle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteBrowsingHistory)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonShowFreeSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectUActionPerformed
        int resultado = gestion.selectUnity(this);
        if (resultado == 0) {
            jLabelSelect.setText("Has seleccionado la ruta: " + gestion.getFile().getAbsolutePath());
            File[] escaneados = gestion.scanUnity(gestion.getFile());
            if (escaneados.length == 0) {
                JOptionPane.showMessageDialog(this, "No hay nada en este directorio.");
            }
        } else {
            jLabelSelect.setText("No se ha seleccionado ningun directorio");
        }
        gestion.convertirArrayEnList();
        ListaDocumentosScanUnity listaDocumentos = new ListaDocumentosScanUnity(this, true, gestion);
        listaDocumentos.setVisible(true);

    }//GEN-LAST:event_jButtonSelectUActionPerformed

    private void jButtonDeleteEmplyDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteEmplyDirectoryActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "¿Desea borrar los directorios vacíos de esta ruta?", "Borrar directorios", JOptionPane.YES_NO_OPTION);
        int directoriosBorrados = gestion.confirmDeleteEmptyDirectories(resultado);
        JOptionPane.showMessageDialog(this, "Se han borrado " + gestion.getContadorDirectoriosBorrados() + " directorios vacíos.");
    }//GEN-LAST:event_jButtonDeleteEmplyDirectoryActionPerformed

    private void jButtonShowFreeSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowFreeSpaceActionPerformed
        gestion.checkDiskSpace();
        JOptionPane.showMessageDialog(this, "Espacio total del disco: " + gestion.getTotal() / 1024 / 1024 / 1024 + "GB" + "\n" + "Espacio libre en disco: " + gestion.getLibre() / 1024 / 1024 / 1024 + "GB");
    }//GEN-LAST:event_jButtonShowFreeSpaceActionPerformed

    private void jButtonDeleteRecycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRecycleActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "¿Desea borrar la papelera de reciclaje?", "Borrar papelera", JOptionPane.YES_NO_OPTION);
        int borrados = 0;
        if (resultado == JOptionPane.YES_OPTION) {
            borrados = gestion.emptyTrash();
        }
        if (borrados == 0) {
            JOptionPane.showMessageDialog(this, "No se ha borrado ningun documento de la papelera.");
        } else {
            JOptionPane.showMessageDialog(this, "Se han borrado " + borrados + " documentos de la papelera.");
        }


    }//GEN-LAST:event_jButtonDeleteRecycleActionPerformed

    private void jButtonDeleteBrowsingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBrowsingHistoryActionPerformed
        //opera
        //cargar en memoria todas la rutas del sistema y analizarlas con .getName hasta que encuentre la carpeta que necesito
        //para borrar el caché
        //https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html aqui está la info de la clase Path que es la que divide la ruta en "nombres"

        int resultado = gestion.deleteBrowsingHistory();
        if (resultado > 5) {
            JOptionPane.showMessageDialog(this, "Se ha borrado el historial de navegación.");
        } else {
            JOptionPane.showMessageDialog(this, "El historial de navegación estaba vacío.");
        }


    }//GEN-LAST:event_jButtonDeleteBrowsingHistoryActionPerformed
    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteBrowsingHistory;
    private javax.swing.JButton jButtonDeleteEmplyDirectory;
    private javax.swing.JButton jButtonDeleteRecycle;
    private javax.swing.JButton jButtonSelectU;
    private javax.swing.JButton jButtonShowFreeSpace;
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
